import React, { createContext, useContext, useState, useEffect } from 'react';
import { DEFAULT_OG_IMAGE, SEO_CONFIG } from '@/seo/config';

export type Language = 'az' | 'ru' | 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  az: {
    // Common
    'common.loading': 'Yüklənir...',
    'common.noImage': 'Şəkil yoxdur',
    'services.empty': 'Hələ xidmət yoxdur',
    'services.moreFeatures': '+{{count}} daha...',
    'services.detail.notFound': 'Xidmət tapılmadı',
    'services.detail.backToList': 'Xidmətlərə qayıt',
    'services.detail.relatedCars': 'Bu xidmət üçün uyğun avtomobillər',
    'services.detail.features': 'Xidmətin Xüsusiyyətləri',
    'services.detail.price.perDay': 'Günlük',
    'services.detail.price.perWeek': 'Həftəlik',
    'services.detail.price.perMonth': 'Aylıq',
    'about.storyTitle': 'Bizim Hekayəmiz',
    'about.galleryAlt': 'Şirkət şəkli',
    'cars.search.noResults': 'Nəticə tapılmadı',
    'cars.search.adjustFilters': 'Filterləri dəyişdirərək yenidən axtarış edin',
    'cars.search.resetCategories': 'Kateqoriyaları sıfırla',
    'cars.search.resetDates': 'Tarixi sıfırla',

    // Header
    'nav.home': 'Əsas Səhifə',
    'nav.cars': 'Avtomobillər',
    'nav.services': 'Xidmətlər',
    'nav.about': 'Haqqımızda',
    'nav.contact': 'Əlaqə',
    'nav.blog': 'Məqalələr',
    'nav.reserve': 'Rezerv et',
    
    // Hero
    'hero.title': 'Bakıda Premium Avtomobil İcarəsi',
    'hero.subtitle': 'İcarə maşınlar 55 AZN-dən başlayır',
    'hero.cta': 'İndi Rezerv Et',
    'hero.selectCar': 'İdeal avtomobilinizi seçin',
    'hero.tagline': 'Azərbaycanın birinci dərəcəli avtomobil icarə xidməti',
    'hero.headline.part1': 'Avtomobil icarəsi cəmi',
    'hero.headline.part2': '50₼/gün – depozitsiz',
    'hero.description': 'Avtomobillərimiz bütün tələblərə cavab verir və Azərbaycanda ən sərfəli şərtlərlə depozitsiz icarə təklif edirik.',
    'hero.booking.question': 'Hansı növ avtomobil icarə etmək istəyirsiniz?',
    'hero.booking.vehicleType': 'Avtomobil növü',
    'hero.booking.search': 'Axtar',
    'hero.booking.pickupLocation': 'Götürmə Yeri',
    'hero.booking.dropoffLocation': 'Qaytarma Yeri',
    'hero.booking.pickupDate': 'Götürmə Tarixi',
    'hero.booking.returnDate': 'Qaytarma Tarixi',
    'hero.booking.vehicle.car': 'Avtomobil',
    'hero.booking.vehicle.van': 'Furgon',
    'hero.booking.vehicle.minibus': 'Minibus',
    'hero.booking.vehicle.prestige': 'Prestij',
    'hero.booking.location.office': 'Baş Ofis',
    'hero.booking.location.airport': 'Hava Limanı',
    'hero.booking.location.hotel': 'Bakıda istənilən otel',
    
    // CTA Weather
    'cta.weather.title': 'HAVA PROQNOZU',
    'cta.weather.description': 'Planlarınız havadan asılı deyil — biz sizi hər şəraitdə təhlükəsiz və rahat yola çıxarırıq.',
    'cta.weather.comprehensive.title.part1': 'Hava',
    'cta.weather.comprehensive.title.part2': 'Proqnozu',
    'cta.weather.comprehensive.subtitle': 'Planlarınız havadan asılı deyil — biz sizi hər şəraitdə təhlükəsiz və rahat yola çıxarırıq.',
    'cta.weather.loading': 'Yüklənir...',
    'cta.weather.wind': 'külək',
    'cta.weather.error': 'Hava məlumatları yüklənə bilmədi',
    
    // Services
    'services.title': 'Xidmətlərimiz',
    // New Services (Comprehensive)
    'services.comprehensive.title.part1': 'Geniş',
    'services.comprehensive.title.part2': 'Avtomobil İcarəsi',
    'services.comprehensive.title.part3': 'Ehtiyaclarınızı Ödəyən Xidmətlər',
    'services.comprehensive.subtitle': 'Günlük icarəsindən uzunmüddətli həllərə qədər, hər ehtiyac və büdcəyə uyğun geniş avtomobil və xidmət çeşidimiz var.',
    'services.dailyWeekly.title': 'Günlük və Həftəlik Avtomobil İcarəsi',
    'services.dailyWeekly.desc': 'Qısa müddətli və həftəlik ehtiyaclar üçün məlumatlı icarəsi variantları, tətil və ya iş səfərləri üçün idealdır.',
    'services.longTerm.title': 'Uzunmüddətli İcarəsi',
    'services.longTerm.desc': 'Uzun müddət avtomobil lazım olanlar üçün rahat və sərfəli həllər, endirimli tariflərlə.',
    'services.luxury.title': 'Lüks Avtomobil İcarəsi',
    'services.luxury.desc': 'Xüsusi tədbirlər və ya biznes səfərləri üçün mükəmməl olan premium avtomobillərimizlə üslubda sürün.',
    'common.viewDetails': 'Ətraflı Bax',
    'services.rental': 'Avtomobil İcarəsi',
    'services.rental.desc': 'Geniş çeşiddə avtomobillər',
    'services.airport': 'Hava Limanı Transferi',
    'services.airport.desc': '24/7 hava limanı xidməti',
    'services.daily': 'Günlük İcarə',
    'services.daily.desc': 'Əlverişli günlük tariflər',
    'services.driver': 'Şəxsi Sürücü',
    'services.driver.desc': 'Təcrübəli sürücülərimiz',
    'services.subtitle': 'Səyahətlərinizə dəyər qatan,sürüş zövqünüzü yüksəldən xidmətlər',
    'services.whyUs.title': 'Niyə Biz?',
    'services.whyUs.cleanCars.title': '100% Təmiz Avtomobillər',
    'services.whyUs.cleanCars.desc': 'Hər avtomobil təhvil verilməzdən əvvəl detallı təmizlənir və dezinfeksiya edilir',
    'services.whyUs.fastDelivery.title': 'Sürətli Təhvil',
    'services.whyUs.fastDelivery.desc': 'Minimum rəsmiləşdirmə və 30 dəqiqə ərzində avtomobil təhvili',
    'services.whyUs.fullInsurance.title': 'Tam Sığorta',
    'services.whyUs.fullInsurance.desc': 'Bütün avtomobillərimiz tam KASKO sığortası ilə təchiz edilmişdir',
    
    // Cars
    'cars.title': 'Avtomobillərimiz',
    'cars.perDay': 'gün',
    'cars.day': 'gün',
    'cars.viewAll': 'Bütün Avtomobilləri Gör',
    'cars.week': 'həftə',
    'cars.month': 'ay',
    'cars.viewDetails': 'Ətraflı Bax',
    'cars.search': 'Avtomobil axtar...',
    'cars.subtitle': 'Sürüş azadlığını yaşayın-avtomobilinizi indi seçin',
    'cars.found': 'avtomobil tapıldı',
    'cars.comprehensive.title.part1': 'Hər ehtiyaca uyğun',
    'cars.comprehensive.title.part2': 'avtomobillər',
    'cars.comprehensive.subtitle': 'Ekonom sinifdən lüks avtomobillərə qədər hər ehtiyaca uyğun geniş avtomobil seçimimiz var.',
    'cars.price': 'Qiymət aralığı',
    'cars.price.all': 'Bütün qiymətlər',
    'cars.reset': 'Sıfırla',
    'cars.noResults': 'Axtarış nəticəsində avtomobil tapılmadı',
    'cars.header': 'Geniş avtomobil parkımızdan seçim edin',
    'cars.loadMore': 'Daha çox göstər',
    
    // Car Detail
    'detail.specs': 'Texniki Xüsusiyyətlər',
    'detail.seats': 'Oturacaq',
    'detail.year': 'İl',
    'detail.fuel': 'Yanacaq',
    'detail.price': 'Günlük Qiymət',
    'detail.deposit': 'Depozit',
    'detail.features': 'Xüsusiyyətlər',
    'detail.gallery': 'Foto Qalereya',
    'detail.reserve': 'İndi Rezerv Et',
    
    // Reviews
    'reviews.title': 'Müştəri Rəyləri',
    'reviews.subtitle': 'Real müştərilərimizin fikirləri',
    'reviews.comprehensive.title.part1': 'Müştərilərimizin',
    'reviews.comprehensive.title.part2': 'Rəyləri',
    'reviews.comprehensive.subtitle': 'Minlərlə məmnun müştərimiz bizimlə təcrübələrini paylaşır. Real rəyləri oxuyun və özünüz qərar verin.',
    'reviews.reviews': 'rəy',
    'reviews.verified': 'Təsdiqlənmiş',
    'reviews.gridView': 'Grid Görünüşü',
    'reviews.sliderView': 'Slider Görünüşü',
    'reviews.showVideos': 'Videoları Göstər',
    'reviews.hideVideos': 'Videoları Gizlət',
    'reviews.card1.title': 'Asan başa düşülən',
    'reviews.card2.title': 'Sürətli və istifadəsi rahat',
    'reviews.card3.title': 'Çox rahat',
    'reviews.review1.text': 'Rezervasiya prosesindəki diqqətlilik səyahətimizi stresssiz etdi və bizə birlikdə unudulmaz xatirələr yaratmağa imkan verdi.',
    'reviews.review2.text': 'Əvvəl çoxlu avtomobil icarə platformalarından istifadə etmişəm, amma bizim rezervasiya sistemimiz ən yaxşısıdır! Proses çox asan və başa düşüləndir.',
    'reviews.review3.text': 'Hər şey aydın şəkildə təqdim olunub və çoxlu ödəniş seçimləri var, bu da hər şeyi çox rahatlaşdırır.',
    'reviews.review4.text': 'Əla əlaqə və tez götürmə. Avtomobil təmiz və yanacaq səmərəli idi. Növbəti səfərimdə yenidən icarəyə götürəcəyəm.',
    'reviews.review5.text': 'Rezervasiya iki dəqiqədən az müddətdə başa çatdı və hər şey təsvirə uyğun oldu. Dəstək xidməti mehriban və faydalı idi.',
    'reviews.review6.text': 'Çoxlu ödəniş seçimləri və aydın qaydalar. Avtomobili qaytarmaq rahat və çox əlverişli idi.',
    'reviews.review7.text': 'Həftəsonu səfəri üçün mükəmməl. Bütün təcrübə başdan sona asan və yaxşı təşkil edilmiş hiss olunurdu.',
    'reviews.review8.text': 'Hava limanında sürətli götürmə və avtomobil gözləntilərimizi aşdı. Mükəmməl qiymət-keyfiyyət nisbəti.',
    'reviews.video': 'Video',
    
    // Contact
    'contact.title': 'Bizimlə Əlaqə',
    'contact.comprehensive.title.part1': 'Bizimlə',
    'contact.comprehensive.title.part2': 'Əlaqə Saxlayın',
    'contact.comprehensive.subtitle': 'Suallarınız və ya xüsusi tələbləriniz var? Komandamız sizə kömək etməyə hazırdır.',
    'contact.name': 'Adınız',
    'contact.email': 'E-mail',
    'contact.message': 'Mesajınız',
    'contact.send': 'Göndər',
    'contact.phone': 'Telefon',
    'contact.office': 'Ofis',
    'contact.address': 'Ünvan',
    'contact.hoursTitle': 'İş saatları',

    
    // Footer
    'footer.description': 'Bakıda ən etibarlı avtomobil icarə xidməti',
    'footer.links': 'Keçidlər',
    'footer.legal': 'Hüquqi',
    'footer.terms': 'İstifadə Qaydaları',
    'footer.privacy': 'Məxfilik Siyasəti',
    'footer.rights': '© 2024 CARRENTBAKU.AZ. Bütün hüquqlar qorunur.',
    
    // About
    'about.title': 'Haqqımızda',
    'about.subtitle': '2016-cı ildən etibar və keyfiyyət',
    'about.tagline': 'Səyahətiniz bizə əmanətdir- 2016cı ildən etibarlı xidmət, keyfiyyətli avtomobillər və məmnuniyyət zəmanəti ilə',
    'about.description': 'CARRENTBAKU.AZ olaraq, 2016-cı ildən Bakıda premium avtomobil icarə xidməti təqdim edirik. Müştəri məmnuniyyəti bizim prioritetimizdir.',
    
    // CTA
    'cta.title': 'İdeal Avtomobilinizi Seçin',
    'cta.subtitle': 'Bakının ən yaxşı avtomobil icarə xidməti',
    'cta.button': 'İndi Əlaqə Saxlayın',
    'cta.floating.buttonLabel': 'Bizə WhatsApp yaz',
    'cta.floating.title': 'Bizimlə əlaqə saxlayın',
    'cta.floating.subtitle': 'Ən uyğun əlaqə kanalını seçin',
    'cta.floating.whatsapp': 'WhatsApp ilə əlaqə',
    'cta.floating.telegram': 'Telegram yazışı',
    'cta.floating.email': 'E-mail göndər',
    'cta.floating.phone': 'Zəng et',
    
    // Blog
    'blog.mainTitle': 'Yeniliklər və məqalələr',
    'blog.title': 'Məqalələr',
    'blog.subtitle': 'Ən son xəbərlər və bloq yazıları',
    'blog.readMore': 'Daha ətraflı oxu',
    'blog.keepReading': 'Daha çox oxu',
    'blog.meta.date': 'tarix',
    'blog.meta.readTime': 'dəq oxu',
    'blog.meta.comments': 'şərhlər',
    'blog.author': 'Yazar',
    'blog.categories.news': 'Yeniliklər',
    'blog.categories.blogs': 'Bloq yazıları',
    'blog.loading': 'Yüklənir...',
    'blog.empty': 'Bu bölmədə hələ məqalə yoxdur',
    'blog.noImage': 'Şəkil yoxdur',
    'blog.notFound': 'Məqalə tapılmadı',
    'blog.backToList': 'Məqalələrə qayıt',
    'blog.relatedTitle': 'Oxşar yazılar',
    'blog.pagination.previous': 'Əvvəlki',
    'blog.pagination.next': 'Növbəti',
    
    // Reservation
    'reservation.title': 'Avtomobil rezervasiyası et',
    'reservation.forCar': 'üçün rezervasiya et',
    'reservation.startDate': 'Başlama tarixi',
    'reservation.endDate': 'Bitmə tarixi',
    'reservation.select': 'Seçin',
    'reservation.pickupLocation': 'Götürmə yeri',
    'reservation.dropoffLocation': 'Qaytarma yeri',
    'reservation.selectLocation': 'Yer seçin',
    'reservation.location.office': 'Baş ofis',
    'reservation.location.airport': 'Hava limanı',
    'reservation.location.hotel': 'Bakıda istənilən hotel',
    'reservation.additionalOptions': 'Əlavə seçimlər',
    'reservation.options.childSeat': 'Uşaq oturacağı',
    'reservation.options.videoRecorder': 'Video qeydiyyatçı',
    'reservation.submit': 'Rezervasiya Et',
    'reservation.error': 'Xəta',
    'reservation.fillAll': 'Zəhmət olmasa bütün xanaları doldurun',
    'reservation.success': 'Uğurlu!',
    'reservation.successMsg': 'Rezervasiyanız qeydə alındı. Tezliklə sizinlə əlaqə saxlanılacaq.',
    'reservation.namePlaceholder': 'Adınız və soyadınız',
    'reservation.subtitle': 'Rezervasiya formunu doldurun, komandamız sizinlə əlaqə saxlasın',
    'reservation.selectCountryCode': 'Ölkə kodunu seçin',
    'reservation.searchCountryCode': 'Ölkə kodu üzrə axtar',
    'reservation.noCountryResults': 'Uyğun ölkə tapılmadı',
    'reservation.phoneNumberPlaceholder': 'Telefon nömrəsi',
    'reservation.totalPrice': 'Ümumi qiymət',
    'reservation.submitting': 'Göndərilir...',
    'common.back': 'Geri qayıt',
    
    // Car Categories
    'cars.filter.all': 'Hamısı',
    'cars.filter.econom': 'Econom',
    'cars.filter.mediumSedan': 'Medium Sedan',
    'cars.filter.suv': 'SUV tipli avtomobillər',
    'cars.filter.minivan': 'Minivanlar',
    'cars.filter.luxury': 'Luxury',
    'cars.filter.bigBus': 'Big Bus',
    
    // FAQ
    'faq.title': 'Tez-tez verilən suallar',
    'faq.q1': 'Avtomobil icarə etmək üçün hansı sənədlər lazımdır?',
    'faq.a1': 'Avtomobil icarə etmək üçün sizə yalnız sürücülük vəsiqəsi, şəxsiyyət vəsiqəsi və kredit kartı lazımdır. Xarici vətəndaşlar üçün beynəlxalq sürücülük vəsiqəsi tələb olunur.',
    'faq.q2': 'Minimum neçə yaşda avtomobil icarə edə bilərəm?',
    'faq.a2': 'Avtomobil icarə etmək üçün minimum yaş 21-dir. Bəzi premium və lüks avtomobillər üçün minimum yaş 25 ola bilər.',
    'faq.q3': 'Depozit nə zaman qaytarılır?',
    'faq.a3': 'Depozit avtomobili qaytardıqdan sonra 3-5 iş günü ərzində sizin kredit kartınıza qaytarılır. Avtomobilda heç bir ziyan olmadığı təqdirdə depozit tam qaytarılır.',
    'faq.q4': 'Hava limanından avtomobil götürə bilərəmmi?',
    'faq.a4': 'Bəli, biz Heydər Əliyev Beynəlxalq Hava Limanından pulsuz təhvil-təslim xidməti təqdim edirik. Siz avtomobili hava limanından götürüb istədiyiniz yerdə qaytara bilərsiniz.',
    'faq.q5': 'Günlük kilometr limiti varmı?',
    'faq.a5': 'Xeyr, bizim avtomobillərimizdə gündəlik kilometr limiti yoxdur. Siz avtomobili limitsiz istifadə edə bilərsiniz.',
    'faq.q6': 'Avtomobilə əlavə sürücü əlavə edə bilərəmmi?',
    'faq.a6': 'Bəli, əlavə sürücü əlavə etmək mümkündür. Əlavə sürücü üçün kiçik bir ödəniş tələb olunur və o da eyni sənədləri təqdim etməlidir.',
    
    // Feedback
    'feedback.title': 'Rəyinizi bizimlə paylaşın',
    'feedback.subtitle': 'Təcrübənizi bizimlə paylaşmağınızdan məmnun olarıq',
    'feedback.firstName': 'Ad',
    'feedback.firstNamePlaceholder': 'Adınız',
    'feedback.lastName': 'Soyad',
    'feedback.lastNamePlaceholder': 'Soyadınız',
    'feedback.email': 'E-mail',
    'feedback.emailPlaceholder': 'E-mail ünvanınız',
    'feedback.rateServices': 'Xidmətlərimizi qiymətləndirin',
    'feedback.liked': 'Xidmətlərimizdə nə bəyəndiniz',
    'feedback.likedPlaceholder': 'Xidmətlərimizdə nə bəyəndiyinizi yazın...',
    'feedback.improvements': 'Necə təkmilləşdirə bilərik?',
    'feedback.improvementsPlaceholder': 'Təkliflərinizi yazın...',
    'feedback.send': 'Rəy göndər',
    'feedback.error.fillRequired': 'Zəhmət olmasa bütün məcburi sahələri doldurun',
    'feedback.success': 'Rəyiniz uğurla göndərildi! Təşəkkür edirik!',
    
    // Contact additional
    'contact.visitUs': 'BİZİ ZİYARƏT EDİN',
    'contact.sendMessage': 'Mesaj Göndərin',
    'contact.firstNamePlaceholder': 'Adınız',
    'contact.lastNamePlaceholder': 'Soyadınız',
    'contact.emailPlaceholder': 'E-mail ünvanınız',
    'contact.subject': 'Mövzu',
    'contact.subjectPlaceholder': 'Mesajın mövzusu',
    'contact.messagePlaceholder': 'Mesajınızı yazın...',
    'contact.submit': 'Göndər',
    'contact.hours.weekdays': 'B.e. - C.a: 09:00 - 18:00',
    'contact.hours.saturday': 'Şənbə: 10:00 - 16:00',
    'contact.hours.sunday': 'Bazar: Bağlı',
    'contact.error.fillRequired': 'Zəhmət olmasa bütün məcburi sahələri doldurun',
    'contact.error.sendFailed': 'Mesaj göndərilərkən xəta baş verdi. Zəhmət olmasa yenidən cəhd edin.',
    'contact.success': 'Mesajınız uğurla göndərildi! Tezliklə sizinlə əlaqə saxlanılacaq.',
  },
  ru: {
    // Common
    'common.loading': 'Загрузка...',
    'common.noImage': 'Нет изображения',
    'services.empty': 'Пока нет услуг',
    'services.moreFeatures': '+{{count}} ещё...',
    'services.detail.notFound': 'Услуга не найдена',
    'services.detail.backToList': 'Назад к услугам',
    'services.detail.relatedCars': 'Подходящие автомобили для этой услуги',
    'services.detail.features': 'Особенности услуги',
    'services.detail.price.perDay': 'В день',
    'services.detail.price.perWeek': 'В неделю',
    'services.detail.price.perMonth': 'В месяц',
    'about.storyTitle': 'Наша история',
    'about.galleryAlt': 'Изображение компании',
    'cars.search.noResults': 'Ничего не найдено',
    'cars.search.adjustFilters': 'Измените фильтры и попробуйте снова',
    'cars.search.resetCategories': 'Сбросить категории',
    'cars.search.resetDates': 'Сбросить даты',

    // New Services (Comprehensive)
    'services.comprehensive.title.part1': 'Комплексные',
    'services.comprehensive.title.part2': 'Аренда авто',
    'services.comprehensive.title.part3': 'для любых ваших потребностей',
    'services.comprehensive.subtitle': 'От краткосрочной аренды до долгосрочных решений — у нас есть варианты для любого бюджета и задачи.',
    'services.dailyWeekly.title': 'Ежедневная и недельная аренда',
    'services.dailyWeekly.desc': 'Гибкие условия аренды на короткий и недельный срок — для отдыха и деловых поездок.',
    'services.longTerm.title': 'Долгосрочная аренда',
    'services.longTerm.desc': 'Удобные и выгодные решения для длительного пользования автомобилем.',
    'services.luxury.title': 'Аренда люксовых авто',
    'services.luxury.desc': 'Премиальные автомобили для особых случаев и представительских поездок.',
    'common.viewDetails': 'Подробнее',
    'nav.home': 'Главная',
    'nav.cars': 'Автомобили',
    'nav.services': 'Услуги',
    'nav.about': 'О нас',
    'nav.contact': 'Контакты',
    'nav.blog': 'Статьи',
    'nav.reserve': 'Забронировать',
    
    'hero.title': 'Премиум аренда авто в Баку',
    'hero.subtitle': 'Аренда авто от 55 AZN',
    'hero.cta': 'Забронировать сейчас',
    'hero.selectCar': 'Выберите идеальный автомобиль',
    'hero.tagline': 'Аренда автомобилей первого класса в Азербайджане',
    'hero.headline.part1': 'Аренда авто всего от',
    'hero.headline.part2': '50₼ в день — без депозита',
    'hero.description': 'Наши автомобили соответствуют всем требованиям, а мы предлагаем аренду на самых выгодных условиях по всей территории Азербайджана.',
    'hero.booking.question': 'Какой тип автомобиля вы хотели бы арендовать?',
    'hero.booking.vehicleType': 'Тип автомобиля',
    'hero.booking.search': 'Найти авто',
    'hero.booking.pickupLocation': 'Место получения',
    'hero.booking.dropoffLocation': 'Место возврата',
    'hero.booking.pickupDate': 'Дата получения',
    'hero.booking.returnDate': 'Дата возврата',
    'hero.booking.vehicle.car': 'Автомобиль',
    'hero.booking.vehicle.van': 'Фургон',
    'hero.booking.vehicle.minibus': 'Минивэн',
    'hero.booking.vehicle.prestige': 'Престиж',
    'hero.booking.location.office': 'Главный офис',
    'hero.booking.location.airport': 'Аэропорт',
    'hero.booking.location.hotel': 'Любой отель в Баку',
    
    // CTA Weather
    'cta.weather.title': 'ПРОГНОЗ ПОГОДЫ',
    'cta.weather.description': 'Ваши планы не зависят от погоды — мы доставим вас безопасно и комфортно в любую погоду.',
    'cta.weather.comprehensive.title.part1': 'Прогноз',
    'cta.weather.comprehensive.title.part2': 'Погоды',
    'cta.weather.comprehensive.subtitle': 'Ваши планы не зависят от погоды — мы доставим вас безопасно и комфортно в любую погоду.',
    'cta.weather.loading': 'Загрузка...',
    'cta.weather.wind': 'ветер',
    'cta.weather.error': 'Не удалось загрузить данные о погоде',
    
    'services.title': 'Наши услуги',
    'services.rental': 'Аренда автомобилей',
    'services.rental.desc': 'Широкий выбор автомобилей',
    'services.airport': 'Трансфер из аэропорта',
    'services.airport.desc': 'Услуги 24/7',
    'services.daily': 'Посуточная аренда',
    'services.daily.desc': 'Выгодные тарифы',
    'services.driver': 'Личный водитель',
    'services.driver.desc': 'Опытные водители',
    'services.subtitle': 'Услуги, которые добавляют ценности вашим поездкам и повышают удовольствие от вождения',
    'services.whyUs.title': 'Почему мы?',
    'services.whyUs.cleanCars.title': '100% Чистые автомобили',
    'services.whyUs.cleanCars.desc': 'Каждый автомобиль тщательно очищается и дезинфицируется перед выдачей',
    'services.whyUs.fastDelivery.title': 'Быстрая выдача',
    'services.whyUs.fastDelivery.desc': 'Минимальное оформление и выдача автомобиля в течение 30 минут',
    'services.whyUs.fullInsurance.title': 'Полная страховка',
    'services.whyUs.fullInsurance.desc': 'Все наши автомобили оснащены полной страховкой КАСКО',
    
    'cars.title': 'Популярные автомобили',
    'cars.perDay': 'день',
    'cars.day': 'день',
    'cars.week': 'неделя',
    'cars.month': 'месяц',
    'cars.viewAll': 'Все автомобили',
    'cars.viewDetails': 'Подробнее',
    'cars.comprehensive.title.part1': 'Широкий Выбор',
    'cars.comprehensive.title.part2': 'Автомобилей',
    'cars.comprehensive.subtitle': 'От эконом-класса до люксовых автомобилей — у нас есть широкий выбор для любых потребностей.',
    'cars.filter.all': 'Все',
    'cars.filter.econom': 'Эконом',
    'cars.filter.mediumSedan': 'Medium Sedan',
    'cars.filter.suv': 'SUV',
    'cars.filter.minivan': 'Минивэн',
    'cars.filter.luxury': 'Люкс',
    'cars.filter.bigBus': 'Большой автобус',
    'cars.search': 'Поиск авто...',
    'cars.subtitle': 'Испытайте свободу вождения - выберите автомобиль сейчас',
    'cars.found': 'автомобилей найдено',
    'cars.price': 'Диапазон цен',
    'cars.price.all': 'Все цены',
    'cars.reset': 'Сбросить',
    'cars.noResults': 'Автомобили не найдены',
    'cars.header': 'Выберите из широкого парка автомобилей',
    'cars.loadMore': 'Показать больше',
    
    'detail.specs': 'Технические характеристики',
    'detail.seats': 'Мест',
    'detail.year': 'Год',
    'detail.fuel': 'Топливо',
    'detail.price': 'Цена в день',
    'detail.deposit': 'Депозит',
    'detail.features': 'Особенности',
    'detail.gallery': 'Фотогалерея',
    'detail.reserve': 'Забронировать',
    
    'reviews.title': 'Отзывы клиентов',
    'reviews.subtitle': 'Мнения наших клиентов',
    'reviews.comprehensive.title.part1': 'Отзывы Наших',
    'reviews.comprehensive.title.part2': 'Клиентов',
    'reviews.comprehensive.subtitle': 'Тысячи довольных клиентов делятся своим опытом с нами. Читайте настоящие отзывы и решайте сами.',
    'reviews.reviews': 'отзывов',
    'reviews.verified': 'Подтверждено',
    'reviews.gridView': 'Сетка',
    'reviews.sliderView': 'Слайдер',
    'reviews.showVideos': 'Показать видео',
    'reviews.hideVideos': 'Скрыть видео',
    'reviews.card1.title': 'Понятно и просто',
    'reviews.card2.title': 'Быстро и удобно',
    'reviews.card3.title': 'Супер удобно',
    'reviews.review1.text': 'Внимание к деталям в процессе бронирования сделало нашу поездку беззаботной, позволив нам сосредоточиться на создании незабываемых воспоминаний вместе.',
    'reviews.review2.text': 'Я использовал много платформ для аренды автомобилей раньше, но наша система бронирования определенно лучшая! Процесс очень простой и понятный.',
    'reviews.review3.text': 'Все четко изложено, и есть множество вариантов оплаты, что делает все очень удобным.',
    'reviews.review4.text': 'Отличное общение и быстрая подача. Автомобиль был чистым и экономичным. Обязательно возьму в аренду в следующей поездке.',
    'reviews.review5.text': 'Бронирование заняло менее двух минут, и все соответствовало описанию. Поддержка была дружелюбной и полезной.',
    'reviews.review6.text': 'Множество вариантов оплаты и четкие правила. Возврат автомобиля был простым и очень удобным.',
    'reviews.review7.text': 'Идеально для выходных. Весь опыт был легким и хорошо организованным от начала до конца.',
    'reviews.review8.text': 'Быстрая подача в аэропорту, и автомобиль превзошел ожидания. Отличное соотношение цены и качества.',
    'reviews.video': 'Видео',
    
    'contact.title': 'Свяжитесь с нами',
    'contact.comprehensive.title.part1': 'Свяжитесь',
    'contact.comprehensive.title.part2': 'С Нами',
    'contact.comprehensive.subtitle': 'У вас есть вопросы или особые требования? Наша команда готова помочь вам.',
    'contact.name': 'Ваше имя',
    'contact.email': 'E-mail',
    'contact.message': 'Ваше сообщение',
    'contact.send': 'Отправить',
    'contact.phone': 'Телефон',
    'contact.office': 'Офис',
    'contact.address': 'Адрес',
    'contact.hoursTitle': 'График работы',

    
    'footer.description': 'Самый надежный сервис аренды авто в Баку',
    'footer.links': 'Ссылки',
    'footer.legal': 'Юридическая информация',
    'footer.terms': 'Условия использования',
    'footer.privacy': 'Политика конфиденциальности',
    'footer.rights': '© 2024 CARRENTBAKU.AZ. Все права защищены.',
    
    'about.title': 'О нас',
    'about.subtitle': 'Доверие и качество с 2016 года',
    'about.tagline': 'Ваше путешествие - наше доверие - с 2016 года надежный сервис, качественные автомобили и гарантия удовлетворенности',
    'about.description': 'CARRENTBAKU.AZ предоставляет премиум услуги аренды автомобилей в Баку с 2016 года. Удовлетворенность клиентов - наш приоритет.',
    
    'cta.title': 'Выберите идеальный автомобиль',
    'cta.subtitle': 'Лучший сервис аренды авто в Баку',
    'cta.button': 'Связаться сейчас',
    'cta.floating.buttonLabel': 'Написать нам в WhatsApp',
    'cta.floating.title': 'Свяжитесь с нами',
    'cta.floating.subtitle': 'Выберите удобный канал связи',
    'cta.floating.whatsapp': 'Написать в WhatsApp',
    'cta.floating.telegram': 'Сообщение в Telegram',
    'cta.floating.email': 'Отправить письмо',
    'cta.floating.phone': 'Позвонить нам',
    
    'blog.mainTitle': 'Новости и статьи',
    'blog.title': 'Статьи',
    'blog.subtitle': 'Актуальные новости и материалы блога',
    'blog.readMore': 'Подробнее',
    'blog.keepReading': 'Читать далее',
    'blog.meta.date': 'дата',
    'blog.meta.readTime': 'мин чтения',
    'blog.meta.comments': 'комментарии',
    'blog.author': 'Автор',
    'blog.categories.news': 'Новости',
    'blog.categories.blogs': 'Блог',
    'blog.loading': 'Загрузка...',
    'blog.empty': 'В этой категории пока нет материалов',
    'blog.noImage': 'Нет изображения',
    'blog.notFound': 'Материал не найден',
    'blog.backToList': 'Вернуться к статьям',
    'blog.relatedTitle': 'Похожие материалы',
    'blog.pagination.previous': 'Предыдущая',
    'blog.pagination.next': 'Следующая',
    
    // Reservation
    'reservation.title': 'Бронирование автомобиля',
    'reservation.forCar': 'бронирование',
    'reservation.startDate': 'Дата начала',
    'reservation.endDate': 'Дата окончания',
    'reservation.select': 'Выберите',
    'reservation.pickupLocation': 'Место получения',
    'reservation.dropoffLocation': 'Место возврата',
    'reservation.selectLocation': 'Выберите место',
    'reservation.location.office': 'Главный офис',
    'reservation.location.airport': 'Аэропорт',
    'reservation.location.hotel': 'Любой отель в Баку',
    'reservation.additionalOptions': 'Дополнительные опции',
    'reservation.options.childSeat': 'Детское кресло',
    'reservation.options.videoRecorder': 'Видеорегистратор',
    'reservation.submit': 'Забронировать',
    'reservation.error': 'Ошибка',
    'reservation.fillAll': 'Пожалуйста, заполните все поля',
    'reservation.success': 'Успешно!',
    'reservation.successMsg': 'Ваше бронирование принято. Мы свяжемся с вами в ближайшее время.',
    'reservation.namePlaceholder': 'Ваше имя и фамилия',
    'reservation.subtitle': 'Заполните форму бронирования, и мы свяжемся с вами',
    'reservation.selectCountryCode': 'Выберите код страны',
    'reservation.searchCountryCode': 'Поиск кода страны',
    'reservation.noCountryResults': 'Страна не найдена',
    'reservation.phoneNumberPlaceholder': 'Номер телефона',
    'reservation.totalPrice': 'Итоговая стоимость',
    'reservation.submitting': 'Отправка...',
    'common.back': 'Назад',
    
    // FAQ
    'faq.title': 'Часто задаваемые вопросы',
    'faq.q1': 'Какие документы нужны для аренды автомобиля?',
    'faq.a1': 'Для аренды автомобиля вам понадобятся только водительские права, удостоверение личности и кредитная карта. Для иностранных граждан требуются международные водительские права.',
    'faq.q2': 'С какого возраста можно арендовать автомобиль?',
    'faq.a2': 'Минимальный возраст для аренды автомобиля - 21 год. Для некоторых премиум и люксовых автомобилей минимальный возраст может быть 25 лет.',
    'faq.q3': 'Когда возвращается депозит?',
    'faq.a3': 'Депозит возвращается на вашу кредитную карту в течение 3-5 рабочих дней после возврата автомобиля. При отсутствии повреждений депозит возвращается полностью.',
    'faq.q4': 'Можно ли получить автомобиль в аэропорту?',
    'faq.a4': 'Да, мы предоставляем бесплатную услугу доставки и получения автомобиля в Международном аэропорту Гейдара Алиева. Вы можете забрать автомобиль в аэропорту и вернуть его в любом месте.',
    'faq.q5': 'Есть ли дневной лимит километража?',
    'faq.a5': 'Нет, наши автомобили не имеют дневного лимита километража. Вы можете использовать автомобиль без ограничений.',
    'faq.q6': 'Можно ли добавить дополнительного водителя?',
    'faq.a6': 'Да, можно добавить дополнительного водителя. За дополнительного водителя взимается небольшая плата, и он должен предоставить те же документы.',
    
    // Feedback
    'feedback.title': 'Оставьте свой отзыв',
    'feedback.subtitle': 'Мы будем рады услышать о вашем опыте',
    'feedback.firstName': 'Имя',
    'feedback.firstNamePlaceholder': 'Ваше имя',
    'feedback.lastName': 'Фамилия',
    'feedback.lastNamePlaceholder': 'Ваша фамилия',
    'feedback.email': 'E-mail',
    'feedback.emailPlaceholder': 'Ваш e-mail адрес',
    'feedback.rateServices': 'Оцените наши услуги',
    'feedback.liked': 'Что вам понравилось в наших услугах',
    'feedback.likedPlaceholder': 'Напишите, что вам понравилось...',
    'feedback.improvements': 'Как мы можем улучшить?',
    'feedback.improvementsPlaceholder': 'Ваши предложения...',
    'feedback.send': 'Отправить отзыв',
    'feedback.error.fillRequired': 'Пожалуйста, заполните все обязательные поля',
    'feedback.success': 'Ваш отзыв успешно отправлен! Спасибо!',
    
    // Contact additional
    'contact.visitUs': 'ПОСЕТИТЕ НАС',
    'contact.sendMessage': 'Отправить сообщение',
    'contact.firstNamePlaceholder': 'Ваше имя',
    'contact.lastNamePlaceholder': 'Ваша фамилия',
    'contact.emailPlaceholder': 'Ваш e-mail адрес',
    'contact.subject': 'Тема',
    'contact.subjectPlaceholder': 'Тема сообщения',
    'contact.messagePlaceholder': 'Напишите ваше сообщение...',
    'contact.submit': 'Отправить',
    'contact.hours.weekdays': 'Пн - Пт: 09:00 - 18:00',
    'contact.hours.saturday': 'Суббота: 10:00 - 16:00',
    'contact.hours.sunday': 'Воскресенье: Закрыто',
    'contact.error.fillRequired': 'Пожалуйста, заполните все обязательные поля',
    'contact.error.sendFailed': 'Произошла ошибка при отправке сообщения. Пожалуйста, попробуйте еще раз.',
    'contact.success': 'Ваше сообщение успешно отправлено! Мы свяжемся с вами в ближайшее время.',
  },
  en: {
    // Common
    'common.loading': 'Loading...',
    'common.noImage': 'No image',
    'services.empty': 'No services yet',
    'services.moreFeatures': '+{{count}} more...',
    'services.detail.notFound': 'Service not found',
    'services.detail.backToList': 'Back to services',
    'services.detail.relatedCars': 'Vehicles available for this service',
    'services.detail.features': 'Service Features',
    'services.detail.price.perDay': 'Daily',
    'services.detail.price.perWeek': 'Weekly',
    'services.detail.price.perMonth': 'Monthly',
    'about.storyTitle': 'Our Story',
    'about.galleryAlt': 'Company image',
    'cars.search.noResults': 'No results found',
    'cars.search.adjustFilters': 'Adjust filters and search again',
    'cars.search.resetCategories': 'Reset categories',
    'cars.search.resetDates': 'Reset dates',

    // New Services (Comprehensive)
    'services.comprehensive.title.part1': 'Comprehensive',
    'services.comprehensive.title.part2': 'Car Rental',
    'services.comprehensive.title.part3': 'Services to Meet All Your Needs',
    'services.comprehensive.subtitle': 'From daily rentals to long-term solutions, we offer a comprehensive range of vehicles and services to suit every need and budget.',
    'services.dailyWeekly.title': 'Daily and Weekly Car Rentals',
    'services.dailyWeekly.desc': 'Flexible rental options available for both short-term and weekly needs, ideal for vacations or business trips.',
    'services.longTerm.title': 'Long-Term Rentals',
    'services.longTerm.desc': 'Convenient and cost-effective solutions for those needing a vehicle for an extended period.',
    'services.luxury.title': 'Luxury Car Rentals',
    'services.luxury.desc': 'High-end vehicles for special occasions and executive travel.',
    'common.viewDetails': 'View Details',
    'nav.home': 'Home',
    'nav.cars': 'Cars',
    'nav.services': 'Services',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    'nav.blog': 'Articles',
    'nav.reserve': 'Reserve',
    
    'hero.title': 'Premium Car Rental in Baku',
    'hero.subtitle': 'Car rental from 55 AZN',
    'hero.cta': 'Reserve Now',
    'hero.selectCar': 'Choose Your Ideal Car',
    'hero.tagline': 'First class car rental service in Azerbaijan',
    'hero.headline.part1': 'Rental Cars From Just',
    'hero.headline.part2': '50₼/Day without Deposit',
    'hero.description': 'Our cars meet all required standards and we offer rentals on the most profitable conditions across the Republic of Azerbaijan.',
    'hero.booking.question': 'What type of car would you like to rent?',
    'hero.booking.vehicleType': 'Vehicle Type',
    'hero.booking.search': 'Search cars',
    'hero.booking.pickupLocation': 'Pick Up Location',
    'hero.booking.dropoffLocation': 'Drop Off Location',
    'hero.booking.pickupDate': 'Pick Up Date',
    'hero.booking.returnDate': 'Return Date',
    'hero.booking.vehicle.car': 'Car',
    'hero.booking.vehicle.van': 'Van',
    'hero.booking.vehicle.minibus': 'Minibus',
    'hero.booking.vehicle.prestige': 'Prestige',
    'hero.booking.location.office': 'Main Office',
    'hero.booking.location.airport': 'Airport',
    'hero.booking.location.hotel': 'Any hotel in Baku',
    
    // CTA Weather
    'cta.weather.title': 'WEATHER FORECAST',
    'cta.weather.description': 'Your plans are not weather-dependent — we will get you safely and comfortably on the road in any conditions.',
    'cta.weather.comprehensive.title.part1': 'Weather',
    'cta.weather.comprehensive.title.part2': 'Forecast',
    'cta.weather.comprehensive.subtitle': 'Your plans are not weather-dependent — we will get you safely and comfortably on the road in any conditions.',
    'cta.weather.loading': 'Loading...',
    'cta.weather.wind': 'wind',
    'cta.weather.error': 'Weather data could not be loaded',
    
    'services.title': 'Our Services',
    'services.rental': 'Car Rental',
    'services.rental.desc': 'Wide range of vehicles',
    'services.airport': 'Airport Transfer',
    'services.airport.desc': '24/7 airport service',
    'services.daily': 'Daily Rental',
    'services.daily.desc': 'Affordable daily rates',
    'services.driver': 'Personal Driver',
    'services.driver.desc': 'Experienced drivers',
    'services.subtitle': 'Services that add value to your travels and elevate your driving pleasure',
    'services.whyUs.title': 'Why Choose Us?',
    'services.whyUs.cleanCars.title': '100% Clean Cars',
    'services.whyUs.cleanCars.desc': 'Every car is thoroughly cleaned and disinfected before delivery',
    'services.whyUs.fastDelivery.title': 'Fast Delivery',
    'services.whyUs.fastDelivery.desc': 'Minimum paperwork and car delivery within 30 minutes',
    'services.whyUs.fullInsurance.title': 'Full Insurance',
    'services.whyUs.fullInsurance.desc': 'All our cars are equipped with full CASCO insurance',
    
    'cars.title': 'Popular Cars',
    'cars.perDay': 'day',
    'cars.day': 'day',
    'cars.week': 'week',
    'cars.month': 'month',
    'cars.viewAll': 'View All Cars',
    'cars.viewDetails': 'View Details',
    'cars.comprehensive.title.part1': 'Wide Selection',
    'cars.comprehensive.title.part2': 'Of Cars',
    'cars.comprehensive.subtitle': 'From economy to luxury cars, we have a wide selection for every need.',
    'cars.filter.all': 'All',
    'cars.filter.econom': 'Econom',
    'cars.filter.mediumSedan': 'Medium Sedan',
    'cars.filter.suv': 'SUV Type Cars',
    'cars.filter.minivan': 'Minivans',
    'cars.filter.luxury': 'Luxury',
    'cars.filter.bigBus': 'Big Bus',
    'cars.search': 'Search cars...',
    'cars.subtitle': 'Experience the freedom of driving - choose your car now',
    'cars.found': 'cars found',
    'cars.price': 'Price Range',
    'cars.price.all': 'All prices',
    'cars.reset': 'Reset',
    'cars.noResults': 'No cars found',
    'cars.header': 'Choose from our wide range of vehicles',
    'cars.loadMore': 'Load more',
    
    'detail.specs': 'Specifications',
    'detail.seats': 'Seats',
    'detail.year': 'Year',
    'detail.fuel': 'Fuel',
    'detail.price': 'Daily Rate',
    'detail.deposit': 'Deposit',
    'detail.features': 'Features',
    'detail.gallery': 'Photo Gallery',
    'detail.reserve': 'Reserve Now',
    
    'reviews.title': 'Customer Reviews',
    'reviews.subtitle': 'What our customers say',
    'reviews.comprehensive.title.part1': 'Our Customer',
    'reviews.comprehensive.title.part2': 'Reviews',
    'reviews.comprehensive.subtitle': 'Thousands of satisfied customers share their experience with us. Read real reviews and decide for yourself.',
    'reviews.reviews': 'reviews',
    'reviews.verified': 'Verified',
    'reviews.gridView': 'Grid View',
    'reviews.sliderView': 'Slider View',
    'reviews.showVideos': 'Show Videos',
    'reviews.hideVideos': 'Hide Videos',
    'reviews.card1.title': 'Easy to Understand',
    'reviews.card2.title': 'Fast and Easy to Use',
    'reviews.card3.title': 'Super Convenient',
    'reviews.review1.text': 'The attention to detail in the booking process made our trip stress-free, allowing us to focus on creating lasting memories together.',
    'reviews.review2.text': "I've used many car rental platforms before, but our booking system is hands down the best! The process is so smooth and straightforward.",
    'reviews.review3.text': 'Everything is laid out clearly, and there are multiple payment options, which makes things super convenient.',
    'reviews.review4.text': 'Great communication and quick pickup. The car was clean and fuel-efficient. Will rent again on my next trip.',
    'reviews.review5.text': 'Booking took less than two minutes and everything matched the description. Support was friendly and helpful.',
    'reviews.review6.text': 'Multiple payment choices and clear policies. Returning the vehicle was seamless and super convenient.',
    'reviews.review7.text': 'Perfect for a weekend getaway. The whole experience felt easy and well-organized from start to finish.',
    'reviews.review8.text': 'Fast pickup at the airport and the car exceeded expectations. Excellent value for money.',
    'reviews.video': 'Video',
    
    'contact.title': 'Contact Us',
    'contact.comprehensive.title.part1': 'Contact',
    'contact.comprehensive.title.part2': 'Us',
    'contact.comprehensive.subtitle': 'Have questions or special requirements? Our team is ready to help you.',
    'contact.name': 'Your Name',
    'contact.email': 'E-mail',
    'contact.message': 'Your Message',
    'contact.send': 'Send',
    'contact.phone': 'Phone',
    'contact.office': 'Office',
    'contact.address': 'Address',
    'contact.hoursTitle': 'Working Hours',

    
    'footer.description': 'Most reliable car rental service in Baku',
    'footer.links': 'Links',
    'footer.legal': 'Legal',
    'footer.terms': 'Terms of Service',
    'footer.privacy': 'Privacy Policy',
    'footer.rights': '© 2024 CARRENTBAKU.AZ. All rights reserved.',
    
    'about.title': 'About Us',
    'about.subtitle': 'Trust and quality since 2016',
    'about.tagline': 'Your journey is our trust - since 2016 reliable service, quality cars and satisfaction guarantee',
    'about.description': 'CARRENTBAKU.AZ has been providing premium car rental services in Baku since 2016. Customer satisfaction is our priority.',
    
    'cta.title': 'Choose Your Perfect Car',
    'cta.subtitle': 'Best car rental service in Baku',
    'cta.button': 'Contact Now',
    'cta.floating.buttonLabel': 'Contact us on WhatsApp',
    'cta.floating.title': 'Get in touch',
    'cta.floating.subtitle': 'Choose the channel that suits you best',
    'cta.floating.whatsapp': 'Chat via WhatsApp',
    'cta.floating.telegram': 'Message on Telegram',
    'cta.floating.email': 'Send an email',
    'cta.floating.phone': 'Call us',
    
    'blog.mainTitle': 'News & Articles',
    'blog.title': 'Articles',
    'blog.subtitle': 'Latest company news and blog posts',
    'blog.readMore': 'Read more',
    'blog.keepReading': 'Keep reading',
    'blog.meta.date': 'date',
    'blog.meta.readTime': 'min read',
    'blog.meta.comments': 'comments',
    'blog.author': 'Author',
    'blog.categories.news': 'News',
    'blog.categories.blogs': 'Blog posts',
    'blog.loading': 'Loading...',
    'blog.empty': 'No articles in this category yet',
    'blog.noImage': 'No image',
    'blog.notFound': 'Article not found',
    'blog.backToList': 'Back to articles',
    'blog.relatedTitle': 'Related articles',
    'blog.pagination.previous': 'Previous',
    'blog.pagination.next': 'Next',
    
    // Reservation
    'reservation.title': 'Car Reservation',
    'reservation.forCar': 'reservation',
    'reservation.startDate': 'Start Date',
    'reservation.endDate': 'End Date',
    'reservation.select': 'Select',
    'reservation.pickupLocation': 'Pickup Location',
    'reservation.dropoffLocation': 'Drop-off Location',
    'reservation.selectLocation': 'Select location',
    'reservation.location.office': 'Main office',
    'reservation.location.airport': 'Airport',
    'reservation.location.hotel': 'Any hotel in Baku',
    'reservation.additionalOptions': 'Additional Options',
    'reservation.options.childSeat': 'Child seat',
    'reservation.options.videoRecorder': 'Video recorder',
    'reservation.submit': 'Reserve',
    'reservation.error': 'Error',
    'reservation.fillAll': 'Please fill in all fields',
    'reservation.success': 'Success!',
    'reservation.successMsg': 'Your reservation has been received. We will contact you shortly.',
    'reservation.namePlaceholder': 'Your full name',
    'reservation.subtitle': 'Complete the booking form and our team will contact you',
    'reservation.selectCountryCode': 'Select country code',
    'reservation.searchCountryCode': 'Search country code',
    'reservation.noCountryResults': 'No matching country',
    'reservation.phoneNumberPlaceholder': 'Phone number',
    'reservation.totalPrice': 'Total price',
    'reservation.submitting': 'Submitting...',
    'common.back': 'Back',
    
    // FAQ
    'faq.title': 'Frequently Asked Questions',
    'faq.q1': 'What documents are required to rent a car?',
    'faq.a1': 'To rent a car, you only need a driver\'s license, ID card, and credit card. For foreign citizens, an international driver\'s license is required.',
    'faq.q2': 'What is the minimum age to rent a car?',
    'faq.a2': 'The minimum age to rent a car is 21 years old. For some premium and luxury cars, the minimum age may be 25 years old.',
    'faq.q3': 'When is the deposit refunded?',
    'faq.a3': 'The deposit is refunded to your credit card within 3-5 business days after returning the car. If there is no damage to the car, the deposit is fully refunded.',
    'faq.q4': 'Can I pick up the car at the airport?',
    'faq.a4': 'Yes, we provide free delivery and pickup service at Heydar Aliyev International Airport. You can pick up the car at the airport and return it anywhere.',
    'faq.q5': 'Is there a daily mileage limit?',
    'faq.a5': 'No, our cars have no daily mileage limit. You can use the car unlimited.',
    'faq.q6': 'Can I add an additional driver?',
    'faq.a6': 'Yes, you can add an additional driver. A small fee is required for an additional driver and they must provide the same documents.',
    
    // Feedback
    'feedback.title': 'Give us your feedback',
    'feedback.subtitle': 'We\'d love to hear what you experienced',
    'feedback.firstName': 'First name',
    'feedback.firstNamePlaceholder': 'Your first name',
    'feedback.lastName': 'Last name',
    'feedback.lastNamePlaceholder': 'Your last name',
    'feedback.email': 'Email',
    'feedback.emailPlaceholder': 'Your email address',
    'feedback.rateServices': 'Rate our services',
    'feedback.liked': 'What did you like about our services',
    'feedback.likedPlaceholder': 'Tell us what you liked...',
    'feedback.improvements': 'How can we improve?',
    'feedback.improvementsPlaceholder': 'Your suggestions...',
    'feedback.send': 'Send Feedback',
    'feedback.error.fillRequired': 'Please fill in all required fields',
    'feedback.success': 'Your feedback has been sent successfully! Thank you!',
    
    // Contact additional
    'contact.visitUs': 'VISIT US',
    'contact.sendMessage': 'Send Message',
    'contact.firstNamePlaceholder': 'Your first name',
    'contact.lastNamePlaceholder': 'Your last name',
    'contact.emailPlaceholder': 'Your email address',
    'contact.subject': 'Subject',
    'contact.subjectPlaceholder': 'Message subject',
    'contact.messagePlaceholder': 'Write your message...',
    'contact.submit': 'Submit',
    'contact.hours.weekdays': 'Mon - Fri: 9am - 6pm',
    'contact.hours.saturday': 'Saturday: 10am - 4pm',
    'contact.hours.sunday': 'Sunday: Closed',
    'contact.error.fillRequired': 'Please fill in all required fields',
    'contact.error.sendFailed': 'An error occurred while sending the message. Please try again.',
    'contact.success': 'Your message has been sent successfully! We will contact you shortly.',
  },
  ar: {
    // Common
    'common.loading': 'جارٍ التحميل...',
    'common.noImage': 'لا توجد صورة',
    'services.empty': 'لا توجد خدمات بعد',
    'services.moreFeatures': '+{{count}} المزيد...',
    'services.detail.notFound': 'الخدمة غير موجودة',
    'services.detail.backToList': 'العودة إلى الخدمات',
    'services.detail.relatedCars': 'السيارات المناسبة لهذه الخدمة',
    'services.detail.features': 'مزايا الخدمة',
    'services.detail.price.perDay': 'يوميًا',
    'services.detail.price.perWeek': 'أسبوعيًا',
    'services.detail.price.perMonth': 'شهريًا',
    'about.storyTitle': 'قصتنا',
    'about.galleryAlt': 'صورة الشركة',
    'cars.search.noResults': 'لا توجد نتائج',
    'cars.search.adjustFilters': 'عدّل عوامل التصفية وحاول مرة أخرى',
    'cars.search.resetCategories': 'إعادة تعيين الفئات',
    'cars.search.resetDates': 'إعادة تعيين التواريخ',

    // New Services (Comprehensive)
    'services.comprehensive.title.part1': 'خدمات',
    'services.comprehensive.title.part2': 'تأجير السيارات',
    'services.comprehensive.title.part3': 'الشاملة لتلبية جميع احتياجاتك',
    'services.comprehensive.subtitle': 'من الإيجار اليومي إلى الحلول طويلة الأجل، نوفر مجموعة شاملة من المركبات والخدمات لتناسب كل الاحتياجات والميزانيات.',
    'services.dailyWeekly.title': 'تأجير يومي وأسبوعي للسيارات',
    'services.dailyWeekly.desc': 'خيارات إيجار مرنة للرحلات القصيرة والأسبوعية، مثالية للعطلات أو رحلات العمل.',
    'services.longTerm.title': 'تأجير طويل الأمد',
    'services.longTerm.desc': 'حلول مريحة وفعّالة من حيث التكلفة لمن يحتاج سيارة لفترة طويلة.',
    'services.luxury.title': 'تأجير سيارات فاخرة',
    'services.luxury.desc': 'سيارات فاخرة للمناسبات الخاصة والسفر التنفيذي.',
    'common.viewDetails': 'عرض التفاصيل',
    'nav.home': 'الرئيسية',
    'nav.cars': 'السيارات',
    'nav.services': 'الخدمات',
    'nav.about': 'عن الشركة',
    'nav.contact': 'اتصل بنا',
    'nav.blog': 'المقالات',
    'nav.reserve': 'احجز الآن',
    
    'hero.title': 'تأجير سيارات فاخرة في باكو',
    'hero.subtitle': 'تأجير السيارات من 55 مانات',
    'hero.cta': 'احجز الآن',
    'hero.selectCar': 'اختر سيارتك المثالية',
    'hero.tagline': 'خدمة تأجير سيارات من الدرجة الأولى في أذربيجان',
    'hero.headline.part1': 'تأجير سيارات ابتداءً من',
    'hero.headline.part2': '50 مانات/اليوم بدون وديعة',
    'hero.description': 'سياراتنا مطابقة لجميع المعايير المطلوبة ونوفر لك التأجير بشروط مربحة في جميع أنحاء جمهورية أذربيجان.',
    'hero.booking.question': 'ما نوع السيارة التي ترغب في تأجيرها؟',
    'hero.booking.vehicleType': 'نوع السيارة',
    'hero.booking.search': 'ابحث عن السيارات',
    'hero.booking.pickupLocation': 'مكان الاستلام',
    'hero.booking.dropoffLocation': 'مكان التسليم',
    'hero.booking.pickupDate': 'تاريخ الاستلام',
    'hero.booking.returnDate': 'تاريخ التسليم',
    'hero.booking.vehicle.car': 'سيارة',
    'hero.booking.vehicle.van': 'شاحنة صغيرة',
    'hero.booking.vehicle.minibus': 'حافلة صغيرة',
    'hero.booking.vehicle.prestige': 'فاخرة',
    'hero.booking.location.office': 'المكتب الرئيسي',
    'hero.booking.location.airport': 'المطار',
    'hero.booking.location.hotel': 'أي فندق في باكو',
    
    // CTA Weather
    'cta.weather.title': 'توقعات الطقس',
    'cta.weather.description': 'خططك لا تعتمد على الطقس — سنوصل بأمان وراحة في أي ظروف.',
    'cta.weather.comprehensive.title.part1': 'توقعات',
    'cta.weather.comprehensive.title.part2': 'الطقس',
    'cta.weather.comprehensive.subtitle': 'خططك لا تعتمد على الطقس — سنوصل بأمان وراحة في أي ظروف.',
    'cta.weather.loading': 'جارٍ التحميل...',
    'cta.weather.wind': 'رياح',
    'cta.weather.error': 'تعذر تحميل بيانات الطقس',
    
    'services.title': 'خدماتنا',
    'services.rental': 'تأجير السيارات',
    'services.rental.desc': 'مجموعة واسعة من السيارات',
    'services.airport': 'نقل المطار',
    'services.airport.desc': 'خدمة المطار على مدار الساعة',
    'services.daily': 'تأجير يومي',
    'services.daily.desc': 'أسعار يومية معقولة',
    'services.driver': 'سائق خاص',
    'services.driver.desc': 'سائقون ذوو خبرة',
    'services.subtitle': 'خدمات تضيف قيمة لرحلاتك وترفع متعة القيادة',
    'services.whyUs.title': 'لماذا نحن؟',
    'services.whyUs.cleanCars.title': 'سيارات نظيفة 100%',
    'services.whyUs.cleanCars.desc': 'يتم تنظيف وتطهير كل سيارة بشكل شامل قبل التسليم',
    'services.whyUs.fastDelivery.title': 'تسليم سريع',
    'services.whyUs.fastDelivery.desc': 'حد أدنى من الأوراق وتسليم السيارة في غضون 30 دقيقة',
    'services.whyUs.fullInsurance.title': 'تأمين كامل',
    'services.whyUs.fullInsurance.desc': 'جميع سياراتنا مجهزة بتأمين كاسكو كامل',
    
    'cars.title': 'السيارات الشعبية',
    'cars.perDay': 'يوم',
    'cars.day': 'يوم',
    'cars.week': 'أسبوع',
    'cars.month': 'شهر',
    'cars.viewAll': 'عرض جميع السيارات',
    'cars.viewDetails': 'عرض التفاصيل',
    'cars.comprehensive.title.part1': 'مجموعة واسعة',
    'cars.comprehensive.title.part2': 'من السيارات',
    'cars.comprehensive.subtitle': 'من الاقتصادية إلى السيارات الفاخرة، لدينا مجموعة واسعة لكل احتياج.',
    'cars.filter.all': 'الكل',
    'cars.filter.econom': 'اقتصادي',
    'cars.filter.mediumSedan': 'Medium Sedan',
    'cars.filter.suv': 'SUV',
    'cars.filter.minivan': 'حافلة صغيرة',
    'cars.filter.luxury': 'فاخرة',
    'cars.filter.bigBus': 'حافلة كبيرة',
    'cars.search': 'البحث عن السيارات...',
    'cars.subtitle': 'استمتع بحرية القيادة - اختر سيارتك الآن',
    'cars.found': 'سيارة تم العثور عليها',
    'cars.price': 'نطاق السعر',
    'cars.price.all': 'جميع الأسعار',
    'cars.reset': 'إعادة تعيين',
    'cars.noResults': 'لم يتم العثور على سيارات',
    'cars.header': 'اختر من مجموعة واسعة من السيارات',
    'cars.loadMore': 'عرض المزيد',
    
    'detail.specs': 'المواصفات',
    'detail.seats': 'المقاعد',
    'detail.year': 'السنة',
    'detail.fuel': 'الوقود',
    'detail.price': 'السعر اليومي',
    'detail.deposit': 'التأمين',
    'detail.features': 'المميزات',
    'detail.gallery': 'معرض الصور',
    'detail.reserve': 'احجز الآن',
    
    'reviews.title': 'آراء العملاء',
    'reviews.subtitle': 'ماذا يقول عملاؤنا',
    'reviews.comprehensive.title.part1': 'آراء',
    'reviews.comprehensive.title.part2': 'عملائنا',
    'reviews.comprehensive.subtitle': 'آلاف العملاء الراضين يشاركون تجربتهم معنا. اقرأ التقييمات الحقيقية وقرر بنفسك.',
    'reviews.reviews': 'مراجعة',
    'reviews.verified': 'مؤكد',
    'reviews.gridView': 'عرض الشبكة',
    'reviews.sliderView': 'عرض الشرائح',
    'reviews.showVideos': 'إظهار الفيديوهات',
    'reviews.hideVideos': 'إخفاء الفيديوهات',
    'reviews.card1.title': 'سهل الفهم',
    'reviews.card2.title': 'سريع وسهل الاستخدام',
    'reviews.card3.title': 'مريح للغاية',
    'reviews.review1.text': 'الاهتمام بالتفاصيل في عملية الحجز جعل رحلتنا خالية من الإجهاد، مما سمح لنا بالتركيز على إنشاء ذكريات دائمة معًا.',
    'reviews.review2.text': 'لقد استخدمت العديد من منصات تأجير السيارات من قبل، لكن نظام الحجز الخاص بنا هو بالتأكيد الأفضل! العملية سلسة ومباشرة للغاية.',
    'reviews.review3.text': 'كل شيء واضح وهناك خيارات دفع متعددة، مما يجعل الأمور مريحة للغاية.',
    'reviews.review4.text': 'تواصل رائع واستلام سريع. كانت السيارة نظيفة وموفرة للوقود. سأستأجر مرة أخرى في رحلتي القادمة.',
    'reviews.review5.text': 'استغرق الحجز أقل من دقيقتين وكل شيء تطابق مع الوصف. الدعم كان ودودًا ومفيدًا.',
    'reviews.review6.text': 'خيارات دفع متعددة وسياسات واضحة. كان إرجاع المركبة سلسًا ومريحًا للغاية.',
    'reviews.review7.text': 'مثالي لعطلة نهاية الأسبوع. شعرت التجربة بالكامل بالسهولة والتنظيم الجيد من البداية إلى النهاية.',
    'reviews.review8.text': 'استلام سريع في المطار وتجاوزت السيارة التوقعات. قيمة ممتازة مقابل المال.',
    'reviews.video': 'فيديو',
    
    'contact.title': 'اتصل بنا',
    'contact.comprehensive.title.part1': 'اتصل',
    'contact.comprehensive.title.part2': 'بنا',
    'contact.comprehensive.subtitle': 'هل لديك أسئلة أو متطلبات خاصة؟ فريقنا جاهز لمساعدتك.',
    'contact.name': 'اسمك',
    'contact.email': 'البريد الإلكتروني',
    'contact.message': 'رسالتك',
    'contact.send': 'إرسال',
    'contact.phone': 'الهاتف',
    'contact.office': 'مكتب',
    'contact.address': 'العنوان',
    'contact.hoursTitle': 'ساعات العمل',

    
    'footer.description': 'أكثر خدمة تأجير سيارات موثوقة في باكو',
    'footer.links': 'روابط',
    'footer.legal': 'قانوني',
    'footer.terms': 'شروط الخدمة',
    'footer.privacy': 'سياسة الخصوصية',
    'footer.rights': '© 2024 CARRENTBAKU.AZ. جميع الحقوق محفوظة.',
    
    'about.title': 'عن الشركة',
    'about.subtitle': 'الثقة والجودة منذ 2016',
    'about.tagline': 'رحلتك هي أمانتنا - منذ 2016 خدمة موثوقة، سيارات عالية الجودة وضمان الرضا',
    'about.description': 'تقدم CARRENTBAKU.AZ خدمات تأجير سيارات فاخرة في باكو منذ عام 2016. رضا العملاء هو أولويتنا.',
    
    'cta.title': 'اختر سيارتك المثالية',
    'cta.subtitle': 'أفضل خدمة تأجير سيارات في باكو',
    'cta.button': 'اتصل الآن',
    'cta.floating.buttonLabel': 'تواصل معنا عبر واتساب',
    'cta.floating.title': 'تواصل معنا',
    'cta.floating.subtitle': 'اختر قناة التواصل الأنسب لك',
    'cta.floating.whatsapp': 'تواصل عبر واتساب',
    'cta.floating.telegram': 'أرسل رسالة عبر تيليغرام',
    'cta.floating.email': 'أرسل بريدًا إلكترونيًا',
    'cta.floating.phone': 'اتصل بنا',
    
    'blog.mainTitle': 'الأخبار والمقالات',
    'blog.title': 'المقالات',
    'blog.subtitle': 'أحدث الأخبار ومحتوى المدونة',
    'blog.readMore': 'اقرأ المزيد',
    'blog.keepReading': 'متابعة القراءة',
    'blog.meta.date': 'التاريخ',
    'blog.meta.readTime': 'دقائق القراءة',
    'blog.meta.comments': 'تعليقات',
    'blog.author': 'الكاتب',
    'blog.categories.news': 'الأخبار',
    'blog.categories.blogs': 'مدونة',
    'blog.loading': 'جاري التحميل...',
    'blog.empty': 'لا توجد مقالات في هذه الفئة بعد',
    'blog.noImage': 'لا توجد صورة',
    'blog.notFound': 'المقال غير موجود',
    'blog.backToList': 'العودة إلى المقالات',
    'blog.relatedTitle': 'مقالات ذات صلة',
    'blog.pagination.previous': 'السابق',
    'blog.pagination.next': 'التالي',
    
    // Reservation
    'reservation.title': 'حجز السيارة',
    'reservation.forCar': 'حجز',
    'reservation.startDate': 'تاريخ البداية',
    'reservation.endDate': 'تاريخ الانتهاء',
    'reservation.select': 'اختر',
    'reservation.pickupLocation': 'مكان الاستلام',
    'reservation.dropoffLocation': 'مكان التسليم',
    'reservation.selectLocation': 'اختر المكان',
    'reservation.location.office': 'المكتب الرئيسي',
    'reservation.location.airport': 'المطار',
    'reservation.location.hotel': 'أي فندق في باكو',
    'reservation.additionalOptions': 'خيارات إضافية',
    'reservation.options.childSeat': 'مقعد الأطفال',
    'reservation.options.videoRecorder': 'مسجل فيديو',
    'reservation.submit': 'احجز',
    'reservation.error': 'خطأ',
    'reservation.fillAll': 'يرجى ملء جميع الحقول',
    'reservation.success': 'نجاح!',
    'reservation.successMsg': 'تم استلام حجزك. سنتصل بك قريبًا.',
    'reservation.namePlaceholder': 'اسمك الكامل',
    'reservation.subtitle': 'أكمل نموذج الحجز وسيتواصل معك فريقنا',
    'reservation.selectCountryCode': 'اختر مفتاح الدولة',
    'reservation.searchCountryCode': 'ابحث عن رمز الدولة',
    'reservation.noCountryResults': 'لا توجد دولة مطابقة',
    'reservation.phoneNumberPlaceholder': 'رقم الهاتف',
    'reservation.totalPrice': 'السعر الإجمالي',
    'reservation.submitting': 'جاري الإرسال...',
    'common.back': 'رجوع',
    
    // FAQ
    'faq.title': 'الأسئلة المتكررة',
    'faq.q1': 'ما هي المستندات المطلوبة لاستئجار سيارة؟',
    'faq.a1': 'لاستئجار سيارة، تحتاج فقط إلى رخصة قيادة وبطاقة هوية وبطاقة ائتمان. بالنسبة للمواطنين الأجانب، يلزم رخصة قيادة دولية.',
    'faq.q2': 'ما هو الحد الأدنى لسن استئجار سيارة؟',
    'faq.a2': 'الحد الأدنى لسن استئجار سيارة هو 21 عامًا. بالنسبة لبعض السيارات الفاخرة والفاخرة، قد يكون الحد الأدنى للسن 25 عامًا.',
    'faq.q3': 'متى يتم استرداد الوديعة؟',
    'faq.a3': 'يتم استرداد الوديعة إلى بطاقة الائتمان الخاصة بك في غضون 3-5 أيام عمل بعد إرجاع السيارة. إذا لم يكن هناك ضرر للسيارة، يتم استرداد الوديعة بالكامل.',
    'faq.q4': 'هل يمكنني استلام السيارة في المطار؟',
    'faq.a4': 'نعم، نوفر خدمة توصيل واستلام مجانية في مطار حيدر علييف الدولي. يمكنك استلام السيارة في المطار وإعادتها في أي مكان.',
    'faq.q5': 'هل هناك حد أقصى للمسافة اليومية؟',
    'faq.a5': 'لا، سياراتنا ليس لديها حد أقصى للمسافة اليومية. يمكنك استخدام السيارة بدون حدود.',
    'faq.q6': 'هل يمكنني إضافة سائق إضافي؟',
    'faq.a6': 'نعم، يمكنك إضافة سائق إضافي. يلزم رسوم صغيرة للسائق الإضافي ويجب عليه تقديم نفس المستندات.',
    
    // Feedback
    'feedback.title': 'أعطنا رأيك',
    'feedback.subtitle': 'نود أن نسمع ما واجهته',
    'feedback.firstName': 'الاسم الأول',
    'feedback.firstNamePlaceholder': 'اسمك الأول',
    'feedback.lastName': 'اسم العائلة',
    'feedback.lastNamePlaceholder': 'اسم عائلتك',
    'feedback.email': 'البريد الإلكتروني',
    'feedback.emailPlaceholder': 'عنوان بريدك الإلكتروني',
    'feedback.rateServices': 'قيم خدماتنا',
    'feedback.liked': 'ماذا أعجبك في خدماتنا',
    'feedback.likedPlaceholder': 'أخبرنا بما أعجبك...',
    'feedback.improvements': 'كيف يمكننا التحسين؟',
    'feedback.improvementsPlaceholder': 'اقتراحاتك...',
    'feedback.send': 'إرسال التعليقات',
    'feedback.error.fillRequired': 'يرجى ملء جميع الحقول المطلوبة',
    'feedback.success': 'تم إرسال رأيك بنجاح! شكرا لك!',
    
    // Contact additional
    'contact.visitUs': 'زرنا',
    'contact.sendMessage': 'إرسال رسالة',
    'contact.firstNamePlaceholder': 'اسمك الأول',
    'contact.lastNamePlaceholder': 'اسم عائلتك',
    'contact.emailPlaceholder': 'عنوان بريدك الإلكتروني',
    'contact.subject': 'الموضوع',
    'contact.subjectPlaceholder': 'موضوع الرسالة',
    'contact.messagePlaceholder': 'اكتب رسالتك...',
    'contact.submit': 'إرسال',
    'contact.hours.weekdays': 'الاثنين - الجمعة: 9 صباحاً - 6 مساءً',
    'contact.hours.saturday': 'السبت: 10 صباحاً - 4 مساءً',
    'contact.hours.sunday': 'الأحد: مغلق',
    'contact.error.fillRequired': 'يرجى ملء جميع الحقول المطلوبة',
    'contact.error.sendFailed': 'حدث خطأ أثناء إرسال الرسالة. يرجى المحاولة مرة أخرى.',
    'contact.success': 'تم إرسال رسالتك بنجاح! سنتصل بك قريباً.',
  },
};

const updateMetaTag = (attribute: 'name' | 'property', identifier: string, content: string) => {
  if (typeof document === 'undefined') {
    return;
  }
  let tag = document.head.querySelector<HTMLMetaElement>(`meta[${attribute}="${identifier}"]`);
  if (!tag) {
    tag = document.createElement('meta');
    tag.setAttribute(attribute, identifier);
    document.head.appendChild(tag);
  }
  tag.setAttribute('content', content);
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  useEffect(() => {
    const savedLang = localStorage.getItem('language') as Language;
    if (savedLang && ['az', 'ru', 'en', 'ar'].includes(savedLang)) {
      setLanguage(savedLang);
      document.documentElement.lang = savedLang;
      document.documentElement.dir = savedLang === 'ar' ? 'rtl' : 'ltr';
    } else {
      document.documentElement.lang = 'en';
      document.documentElement.dir = 'ltr';
    }
  }, []);

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
    document.documentElement.lang = lang;
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
  };

  useEffect(() => {
    if (typeof document === 'undefined') {
      return;
    }
    const config = SEO_CONFIG[language];
    if (!config) {
      return;
    }
    const ogTitle = config.ogTitle ?? config.title;
    const ogDescription = config.ogDescription ?? config.description;
    const image = config.image ?? DEFAULT_OG_IMAGE;

    document.title = config.title;
    updateMetaTag('name', 'description', config.description);
    updateMetaTag('name', 'keywords', config.keywords.join(', '));
    updateMetaTag('property', 'og:title', ogTitle);
    updateMetaTag('property', 'og:description', ogDescription);
    updateMetaTag('property', 'og:image', image);
    updateMetaTag('name', 'twitter:title', ogTitle);
    updateMetaTag('name', 'twitter:description', ogDescription);
    updateMetaTag('name', 'twitter:image', image);
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};
