import { prisma } from "../src/lib/prisma";

const BUSINESS_CARS = [
  {
    brand: "Hyundai",
    model: "Sonata",
    year: 2017,
    category: "medium-sedan",
    price_per_day: 80,
    price_per_week: 550,
    fuel_type: "Benzin",
    transmission: "Auto",
    seats: 5,
    image_url: "https://new.carrentbaku.az/placeholder.svg",
    features: ["Automatic transmission", "Fuel: Benzin", "5 seats"],
  },
  {
    brand: "Hyundai",
    model: "Sonata",
    year: 2023,
    category: "medium-sedan",
    price_per_day: 140,
    price_per_week: 900,
    fuel_type: "Benzin",
    transmission: "Auto",
    seats: 5,
    image_url: "https://new.carrentbaku.az/placeholder.svg",
    features: ["Automatic transmission", "Fuel: Benzin", "5 seats"],
  },
  {
    brand: "Kia",
    model: "Optima",
    year: 2019,
    category: "medium-sedan",
    price_per_day: 80,
    price_per_week: 550,
    fuel_type: "Benzin",
    transmission: "Auto",
    seats: 5,
    image_url: "https://new.carrentbaku.az/placeholder.svg",
    features: ["Automatic transmission", "Fuel: Benzin", "5 seats"],
  },
  {
    brand: "Kia",
    model: "K5",
    year: 2023,
    category: "medium-sedan",
    price_per_day: 130,
    price_per_week: 850,
    fuel_type: "Benzin",
    transmission: "Auto",
    seats: 5,
    image_url: "https://new.carrentbaku.az/placeholder.svg",
    features: ["Automatic transmission", "Fuel: Benzin", "5 seats"],
  },
  {
    brand: "BMW",
    model: "530",
    year: 2016,
    category: "medium-sedan",
    price_per_day: 170,
    price_per_week: 1120,
    fuel_type: "Benzin",
    transmission: "Auto",
    seats: 5,
    image_url: "https://new.carrentbaku.az/placeholder.svg",
    features: ["Automatic transmission", "Fuel: Benzin", "5 seats"],
  },
  {
    brand: "Toyota",
    model: "Land Cruiser",
    year: 2020,
    category: "suv",
    price_per_day: 300,
    price_per_week: 2000,
    fuel_type: "Benzin",
    transmission: "Auto",
    seats: 7,
    image_url: "https://new.carrentbaku.az/placeholder.svg",
    features: ["Automatic transmission", "Fuel: Benzin", "7 seats"],
  },
  {
    brand: "Lexus",
    model: "570",
    year: 2022,
    category: "luxury",
    price_per_day: 1400,
    price_per_week: 9100,
    fuel_type: "Benzin",
    transmission: "Auto",
    seats: 7,
    image_url: "https://new.carrentbaku.az/placeholder.svg",
    features: ["Automatic transmission", "Fuel: Benzin", "7 seats"],
  },
  {
    brand: "BMW",
    model: "530",
    year: 2021,
    category: "medium-sedan",
    price_per_day: 350,
    price_per_week: 2300,
    fuel_type: "Benzin",
    transmission: "Auto",
    seats: 5,
    image_url: "https://new.carrentbaku.az/placeholder.svg",
    features: ["Automatic transmission", "Fuel: Benzin", "5 seats"],
  },
  {
    brand: "Mercedes",
    model: "GLS",
    year: 2023,
    category: "suv",
    price_per_day: 350,
    price_per_week: 2400,
    fuel_type: "Benzin",
    transmission: "Auto",
    seats: 5,
    image_url: "https://new.carrentbaku.az/placeholder.svg",
    features: ["Automatic transmission", "Fuel: Benzin", "5 seats"],
  },
  {
    brand: "BMW",
    model: "X5",
    year: 2021,
    category: "suv",
    price_per_day: 350,
    price_per_week: 2400,
    fuel_type: "Benzin",
    transmission: "Auto",
    seats: 5,
    image_url: "https://new.carrentbaku.az/placeholder.svg",
    features: ["Automatic transmission", "Fuel: Benzin", "5 seats"],
  },
  {
    brand: "BMW",
    model: "X7",
    year: 2021,
    category: "luxury",
    price_per_day: 400,
    price_per_week: 2700,
    fuel_type: "Benzin",
    transmission: "Auto",
    seats: 7,
    image_url: "https://new.carrentbaku.az/placeholder.svg",
    features: ["Automatic transmission", "Fuel: Benzin", "7 seats"],
  },
  {
    brand: "Range Rover",
    model: "Vogue",
    year: 2022,
    category: "luxury",
    price_per_day: 350,
    price_per_week: 2300,
    fuel_type: "Benzin",
    transmission: "Auto",
    seats: 5,
    image_url: "https://new.carrentbaku.az/placeholder.svg",
    features: ["Automatic transmission", "Fuel: Benzin", "5 seats"],
  },
  {
    brand: "Toyota",
    model: "Camry",
    year: 2023,
    category: "medium-sedan",
    price_per_day: 130,
    price_per_week: 800,
    fuel_type: "Hybrid",
    transmission: "Auto",
    seats: 5,
    image_url: "https://new.carrentbaku.az/placeholder.svg",
    features: ["Automatic transmission", "Hybrid", "5 seats"],
  },
];

(async () => {
  for (const car of BUSINESS_CARS) {
    const existing = await prisma.car.findFirst({
      where: {
        brand: car.brand,
        model: car.model,
        year: car.year,
      },
    });

    if (existing) {
      await prisma.car.update({
        where: { id: existing.id },
        data: car,
      });
      console.log(`Updated ${car.brand} ${car.model} ${car.year}`);
    } else {
      await prisma.car.create({ data: car });
      console.log(`Created ${car.brand} ${car.model} ${car.year}`);
    }
  }

  await prisma.$disconnect();
})();
